### ISSUE TITLE
yo dashing-go fails with : Error: EACCES, permission denied

### ISSUE THREAD

**Issue by alex-leonhardt** [gigablah/generator-dashing-go#5]
with this error: 

```
 # yo dashing-go

Error: EACCES, permission denied '/root/.config/configstore/insight-yo.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:432:18)
    at Object.fs.writeFileSync (evalmachine.<anonymous>:971:15)
    at Object.create.all.set (/usr/lib/node_modules/yo/node_modules/configstore/index.js:64:8)
    at Object.Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:11)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:36:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:117:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Any ideas ? Those directories don't exist. I created the manually, still won't run.

Thanks!
Alex

**Comment by gigablah** [comment]
This is an issue related to Yeoman. You could try running `yo` as non-root.

https://github.com/yeoman/yeoman.io/issues/282
